services:
  caddy:
    image: caddy:latest
    container_name: caddy-server
    ports:
      - "2025:2025"
    volumes:
      - ./site:/srv            # ton site web
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - php
    restart: unless-stopped

  php:
    image: php:8.1-fpm-alpine
    container_name: php-fpm
    volumes:
      - ./site:/srv
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
